const $=id=>document.getElementById(id);let stack=['home'];let clock={start:null,paused:false,pauseStart:null,pausedMs:0,timer:null};let records=[];
function showScreen(id,btn){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));$(id)?.classList.add('active');document.querySelectorAll('.nav button').forEach(b=>b.classList.remove('active'));if(btn)btn.classList.add('active');else{let m={home:0,doctor:1,parts:2,repair:3,settings:4};let n=document.querySelectorAll('.nav button')[m[id]];if(n)n.classList.add('active')}stack.push(id);$('menu')?.classList.remove('open')}
function goBack(){stack.pop();showScreen(stack.pop()||'home')}function toggleMenu(){$('menu').classList.toggle('open')}function focusAsk(){$('masterAsk').focus()}function setAsk(t){$('masterAsk').value=t;$('masterAsk').focus()}function voiceShell(){alert('Voice input shell ready.')}function openCamera(){$('cameraInput')?.click()}$('cameraInput')?.addEventListener('change',e=>{let f=e.target.files?.[0];if(f)alert('Camera loaded: '+f.name)})
function saveTruck(){let vin=$('vinInput').value.trim()||'1XP4D49X8KD123456',yr=$('yearInput').value.trim()||'2020',mk=$('makeInput').value.trim()||'Freightliner',mo=$('modelInput').value.trim()||'Cascadia',en=$('engineInput').value.trim()||'Cummins X15',esn=$('esnInput').value.trim()||'79876562',cpl=$('cplInput').value.trim()||'4342';$('dashVin').textContent=vin;$('dashTruck').textContent=`${yr} ${mk} ${mo}`;$('dashEngine').textContent=en.toUpperCase();$('dashEsn').textContent=esn;$('dashCpl').textContent=cpl;$('vinOut').textContent='Active truck saved.';localStorage.setItem('rwTruck',JSON.stringify({vin,yr,mk,mo,en,esn,cpl}))}
function loadTruck(){try{let t=JSON.parse(localStorage.getItem('rwTruck')||'null');if(!t)return;$('dashVin').textContent=t.vin;$('dashTruck').textContent=`${t.yr} ${t.mk} ${t.mo}`;$('dashEngine').textContent=t.en.toUpperCase();$('dashEsn').textContent=t.esn;$('dashCpl').textContent=t.cpl}catch(e){}}
function clearTruck(){['vinInput','yearInput','makeInput','modelInput','engineInput','esnInput','cplInput'].forEach(id=>$(id).value='');$('vinOut').textContent='Truck fields cleared.'}
function runParts(){let q=$('partInput').value.trim();$('partsOut').textContent=q?`OEM Parts lookup shell\n\nPart: ${q}\nContext: ${$('partNotes').value||'No notes'}\n\nReady for Supabase Oracle/interchange/kit connection.`:'Enter a part first.'}
function addPartToQuote(){$('quoteNotes').value+='\nPart: '+($('partInput').value||'manual part');$('partsOut').textContent='Part sent to quote.'}
function savePart(){let a=JSON.parse(localStorage.getItem('rwParts')||'[]');a.push({part:$('partInput').value,notes:$('partNotes').value,date:new Date().toLocaleString()});localStorage.setItem('rwParts',JSON.stringify(a));$('partsOut').textContent='Part saved locally.'}
function clearParts(){$('partInput').value='';$('partNotes').value='';$('partsOut').textContent='Parts cleared.'}
function runDoctor(){let q=$('doctorInput').value.trim();$('doctorOut').textContent=q?`Diagnostic shell\n\n${q}\n\nNext: likely causes, tests, common fixes, verified memory.`:'Enter a fault or symptom.'}
function saveFix(){localStorage.setItem('rwFix',JSON.stringify({fault:$('doctorInput').value,notes:$('doctorNotes').value}));$('doctorOut').textContent='Verified fix saved locally.'}
function sendDoctorToQuote(){$('quoteNotes').value+='\nDiagnostic: '+($('doctorInput').value||'');$('doctorOut').textContent='Diagnostic sent to quote.'}
function clearDoctor(){$('doctorInput').value='';$('doctorNotes').value='';$('doctorOut').textContent='Doctor cleared.'}
function repairPlan(){$('repairOut').textContent='Repair plan shell:\n'+($('repairInput').value||'Enter a repair question.')}function torqueShell(){$('repairOut').textContent='Torque/spec shell ready.'}function warnings(){$('repairOut').textContent='Common mistakes shell ready.'}function saveRepairMemory(){localStorage.setItem('rwRepair',$('repairInput').value);$('repairOut').textContent='Repair note saved.'}
function buildQuote(){let h=parseFloat($('laborHours').value||0),r=parseFloat($('laborRate').value||0),c=parseFloat($('serviceCall').value||0),p=parseFloat($('partsCost').value||0),tr=parseFloat($('taxRate').value||0)/100;let sub=h*r+c+p,t=sub*tr,total=sub+t;$('quoteOut').textContent=`ROLLING WRENCH QUOTE\nCustomer: ${$('custName').value||'Customer'}\nLabor: ${h.toFixed(2)} x $${r.toFixed(2)} = $${(h*r).toFixed(2)}\nService Call: $${c.toFixed(2)}\nParts: $${p.toFixed(2)}\nTax: $${t.toFixed(2)}\nTOTAL: $${total.toFixed(2)}\n\nNotes:\n${$('quoteNotes').value||''}`}
function copyQuote(){navigator.clipboard?.writeText($('quoteOut').textContent);$('quoteOut').textContent+='\n\nCopied.'}function saveQuote(){localStorage.setItem('rwQuote',$('quoteOut').textContent);$('quoteOut').textContent+='\n\nSaved.'}function clearQuote(){['custName','laborHours','partsCost','quoteNotes'].forEach(id=>$(id).value='');$('quoteOut').textContent='Quote cleared.'}
function updateClock(){if(!clock.start)return;let now=new Date(),ms=now-clock.start-clock.pausedMs;if(clock.paused)ms=clock.pauseStart-clock.start-clock.pausedMs;let hrs=Math.max(0,ms/3600000);$('clockTimer').textContent=hrs.toFixed(2)+' hrs';$('clockBillable').textContent=hrs.toFixed(2);$('clockTotal').textContent='$'+(hrs*parseFloat($('clockRate').value||0)).toFixed(2)}
function clockIn(){clock={start:new Date(),paused:false,pauseStart:null,pausedMs:0,timer:null};$('clockStatus').textContent='CLOCKED IN';$('clockStart').textContent=clock.start.toLocaleTimeString();$('clockStop').textContent='--';$('clockPaused').textContent='0 min';clearInterval(clock.timer);clock.timer=setInterval(updateClock,1000);updateClock()}
function pauseClock(){if(!clock.start||clock.paused)return;clock.paused=true;clock.pauseStart=new Date();$('clockStatus').textContent='PAUSED'}function resumeClock(){if(!clock.start||!clock.paused)return;clock.pausedMs+=new Date()-clock.pauseStart;clock.paused=false;clock.pauseStart=null;$('clockStatus').textContent='CLOCKED IN';$('clockPaused').textContent=Math.round(clock.pausedMs/60000)+' min'}
function clockOut(){if(!clock.start){$('clockRecordsOut').textContent='Clock not started.';return}if(clock.paused)resumeClock();updateClock();clearInterval(clock.timer);let stop=new Date();$('clockStop').textContent=stop.toLocaleTimeString();$('clockStatus').textContent='CLOCKED OUT';let rec={start:clock.start.toLocaleString(),stop:stop.toLocaleString(),hours:$('clockBillable').textContent,total:$('clockTotal').textContent};records.push(rec);localStorage.setItem('rwTimeRecords',JSON.stringify(records));$('clockRecordsOut').textContent=`Saved: ${rec.hours} hrs / ${rec.total}`}
function sendClockToQuote(){$('laborHours').value=$('clockBillable').textContent;$('clockRecordsOut').textContent='Clock hours sent to quote.'}function showTimeRecords(){records=JSON.parse(localStorage.getItem('rwTimeRecords')||'[]');$('clockRecordsOut').textContent=records.length?records.map((r,i)=>`${i+1}. ${r.hours} ${r.total} | ${r.start}`).join('\n'):'No records.'}function resetClock(){clearInterval(clock.timer);clock={start:null,paused:false,pauseStart:null,pausedMs:0,timer:null};['clockStart','clockStop'].forEach(id=>$(id).textContent='--');$('clockPaused').textContent='0 min';$('clockBillable').textContent='0.00';$('clockTimer').textContent='0.00 hrs';$('clockTotal').textContent='$0.00';$('clockStatus').textContent='CLOCKED OUT'}
function cleanVision(){$('visionOut').textContent='Cleaned text:\n'+($('visionRaw').value||'No raw text.')}function sendVisionToParts(){$('partInput').value=$('visionRaw').value;$('visionOut').textContent='Sent to parts.'}function sendVisionToVin(){$('vinInput').value=$('visionRaw').value;$('visionOut').textContent='Sent to VIN.'}function clearVision(){$('visionRaw').value='';$('visionOut').textContent='Vision cleared.'}
function searchManuals(){$('manualsOut').textContent='Manual search shell: '+($('manualInput').value||'No query')}function saveManualNote(){localStorage.setItem('rwManual',$('manualInput').value);$('manualsOut').textContent='Manual note saved.'}function clearManuals(){$('manualInput').value='';$('manualsOut').textContent='Manuals cleared.'}
function dropGps(){if(!navigator.geolocation){$('gpsOut').textContent='GPS not available.';return}$('gpsOut').textContent='Getting GPS...';navigator.geolocation.getCurrentPosition(p=>$('gpsOut').textContent=`GPS: ${p.coords.latitude.toFixed(6)}, ${p.coords.longitude.toFixed(6)}`,e=>$('gpsOut').textContent='GPS denied/unavailable.')}
function buildDotChecklist(){$('gpsOut').textContent='DOT checklist: lights, brakes, tires, air leaks, fluids, battery, road test.'}function copyCustomerUpdate(){let msg=`Rolling Wrench update: ${$('fieldLocation').value||'job site'} - ${$('fieldNotes').value||'work in progress'}`;navigator.clipboard?.writeText(msg);$('gpsOut').textContent='Copied:\n'+msg}function clearField(){$('fieldLocation').value='';$('fieldNotes').value='';$('gpsOut').textContent='Field cleared.'}
function saveMemory(){let a=JSON.parse(localStorage.getItem('rwMemory')||'[]');a.push({fault:$('memoryFault').value,fix:$('memoryFix').value,date:new Date().toLocaleString()});localStorage.setItem('rwMemory',JSON.stringify(a));$('memoryOut').textContent='Memory saved.'}function loadMemory(){let a=JSON.parse(localStorage.getItem('rwMemory')||'[]');$('memoryOut').textContent=a.length?a.map((m,i)=>`${i+1}. ${m.fault}\n${m.fix}`).join('\n\n'):'No memory saved.'}function clearMemoryFields(){$('memoryFault').value='';$('memoryFix').value='';$('memoryOut').textContent='Memory cleared.'}
function scannerTest(){$('scannerOut').textContent='Bluetooth scanner under construction: 9-pin J1939, OBD2, SPN/FMI, VIN auto detect, voltage, CAN activity.'}
function setTheme(t){document.body.dataset.theme=t;localStorage.setItem('rwTheme',t)}
window.addEventListener('load',()=>{loadTruck();records=JSON.parse(localStorage.getItem('rwTimeRecords')||'[]');if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js').catch(()=>{})})